/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

/**
 *
 * @author alumnadotarde
 */
public class calc extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(calc.class.getName());
    private String op = "";
    private double n1;
    private double n2;

    /**
     * Creates new form calc
     */
    public calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt = new javax.swing.JLabel();
        bC = new javax.swing.JButton();
        bd = new javax.swing.JButton();
        bm = new javax.swing.JButton();
        br = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bs = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        be = new javax.swing.JButton();
        bp = new javax.swing.JButton();
        calc = new Calculadora.Calculadora();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        txt.setBackground(new java.awt.Color(204, 204, 204));
        txt.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        txt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        txt.setOpaque(true);

        bC.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        bC.setText("C");
        bC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCActionPerformed(evt);
            }
        });

        bd.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        bd.setText("/");
        bd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdActionPerformed(evt);
            }
        });

        bm.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        bm.setText("X");
        bm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmActionPerformed(evt);
            }
        });

        br.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        br.setText("-");
        br.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        br.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        br.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        b7.setText("7");
        b7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        b8.setText("8");
        b8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        b9.setText("9");
        b9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        bs.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        bs.setText("+");
        bs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        b4.setText("4");
        b4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        b5.setText("5");
        b5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        b6.setText("6");
        b6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        b1.setText("1");
        b1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        b2.setText("2");
        b2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        b3.setText("3");
        b3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b0.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        b0.setText("0");
        b0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        be.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        be.setText("=");
        be.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        be.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        be.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beActionPerformed(evt);
            }
        });

        bp.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        bp.setText(".");
        bp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        calc.setBackground(new java.awt.Color(0, 0, 0));
        calc.setForeground(new java.awt.Color(255, 255, 255));
        calc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calc.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        calc.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bm, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(br, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(bs, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(b0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(be, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(calc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(calc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(br, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bs, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bp, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(be, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCActionPerformed
        op = "";
        n1 = 0;
        n2 = 0;
        txt.setText("");
        calc.setOp("");
        calc.setN1(0);
        calc.setText("");
    }//GEN-LAST:event_bCActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        if (n1 == 0) {
            n1 = 0;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n1 > 0 && op.isEmpty()) {
            n1 = n1 * 10;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n2 == 0) {
            n2 = 0;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        } else if (n2 > 0 && !op.isEmpty()) {
            n2 = n2 * 10;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        }
    }//GEN-LAST:event_b0ActionPerformed

    private void beActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beActionPerformed
        if (n1 == 0 && n2 == 0 || op.isEmpty()) {

        } else {
            double res = calc.operacion();
            n1 = 0;
            n2 = 0;
            op = "";
            calc.setText("");
            txt.setText(String.valueOf((long)res));
        }
    }//GEN-LAST:event_beActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if (n1 == 0) {
            n1 = 1;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n1 > 0 && op.isEmpty()) {
            n1 = n1 * 10+1;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n2 == 0) {
            n2 = 1;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        } else if (n2 > 0 && !op.isEmpty()) {
            n2 = (n2 * 10)+1;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if (n1 == 0) {
            n1 = 2;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n1 > 0 && op.isEmpty()) {
            n1 = n1 * 10+2;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n2 == 0) {
            n2 = 2;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        } else if (n2 > 0 && !op.isEmpty()) {
            n2 = n2 * 10+2;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if (n1 == 0) {
            n1 = 3;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n1 > 0 && op.isEmpty()) {
            n1 = n1 * 10+3;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n2 == 0) {
            n2 = 3;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        } else if (n2 > 0 && !op.isEmpty()) {
            n2 = n2 * 10+3;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if (n1 == 0) {
            n1 = 4;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n1 > 0 && op.isEmpty()) {
            n1 = n1 * 10 + 4;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n2 == 0) {
            n2 = 4;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        } else if (n2 > 0 && !op.isEmpty()) {
            n2 = n2 * 10 + 4;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if (n1 == 0) {
            n1 = 5;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n1 > 0 && op.isEmpty()) {
            n1 = n1*10+5;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n2 == 0) {
            n2 = 5;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        } else if (n2 > 0 && !op.isEmpty()) {
            n2 = n2 * 10+5;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if (n1 == 0) {
            n1 = 6;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n1 > 0 && op.isEmpty()) {
            n1 = n1 * 10+6;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n2 == 0) {
            n2 = 6;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        } else if (n2 > 0 && !op.isEmpty()) {
            n2 = n2 * 10+6;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if (n1 == 0) {
            n1 = 7;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n1 > 0 && op.isEmpty()) {
            n1 = n1 * 10+7;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n2 == 0) {
            n2 = 7;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        } else if (n2 > 0 && !op.isEmpty()) {
            n2 = n2 * 10+7;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if (n1 == 0) {
            n1 = 8;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n1 > 0 && op.isEmpty()) {
            n1 = n1 * 10+8;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n2 == 0) {
            n2 = 8;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        } else if (n2 > 0 && !op.isEmpty()) {
            n2 = n2 * 10+8;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if (n1 == 0) {
            n1 = 9;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n1 > 0 && op.isEmpty()) {
            n1 = n1 * 10+9;
            calc.setN1(n1);
            txt.setText(String.valueOf((long)n1));
        } else if (n2 == 0) {
            n2 = 9;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        } else if (n2 > 0 && !op.isEmpty()) {
            n2 = n2 * 10+9;
            calc.setN2(n2);
            calc.setText(String.valueOf((long)n1) + op);
            txt.setText(String.valueOf((long)n2));
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdActionPerformed
        op = "/";
        calc.setOp(op);
    }//GEN-LAST:event_bdActionPerformed

    private void bmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmActionPerformed
        op = "*";
        calc.setOp(op);
    }//GEN-LAST:event_bmActionPerformed

    private void brActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brActionPerformed
        op = "-";
        calc.setOp(op);
    }//GEN-LAST:event_brActionPerformed

    private void bsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsActionPerformed
        op = "+";
        calc.setOp(op);
    }//GEN-LAST:event_bsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new calc().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bC;
    private javax.swing.JButton bd;
    private javax.swing.JButton be;
    private javax.swing.JButton bm;
    private javax.swing.JButton bp;
    private javax.swing.JButton br;
    private javax.swing.JButton bs;
    private Calculadora.Calculadora calc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt;
    // End of variables declaration//GEN-END:variables
}
